### ISSUE TITLE
wrong row updated

### ISSUE THREAD

**Issue by hildo714** [mennooo/orclapex-ig-set-items#2]
When you scroll through the grid, the details items get filled with the data, so far so good. But when you update an item and then scroll one row up or one row down, the right column is updated but in the wrong row. I would expect the current row to update instead of the record I'm going to.
How to reproduce this?
I'm on the first row of the grid, I go to the first item ename, let's say this is 'ALLEN'. I change it to ALLEN44. Without leaving the field I now go and click on another row in the grid. Now you will see the wrong row is updated. Hope this explains the issue.
Tested with Chrome on Apex 5.1.1.00.08.

Great plugin though, not easy to get this working. Chapeau!!

**Comment by mennooo** [comment]
Yes, confirmed. The `interactivegridselectionchange` triggers before the `change` event of the item. 

Possible fix: try to use `blur` event for items on this line:

https://github.com/mennooo/orclapex-ig-set-items/blob/bfe5ecea74e29b203799df86137115e8a249839f/server/js/IGSetItems.js#L206
